google:
    json_key: ""        #personal access key (json file)
    worksheet_url: ""    #Google Sheet URL (the link used to share the file)

    sheet : 0  #sheet in which the table is located	
    first_column : A
    last_column : K
    min_read_line : 9
    max_read_line : 600    #TO BE UPDATED WHEN DATABASE UPDATED

data_selection_and_lists:
    time_range : True  #Search for all runs in a LST range (e.g., 2020_01_01 -> 2022_01_01)
    min : "2020_11_17"
    max : "2020_11_19"
   
    date_list : ['2020_12_15','2021_03_11']
                       #LST list of days to be processed (time_range=False), format: YYYY_MM_DD
 
    skipped_LST_runs: [2919,2923]
    skipped_MAGIC_runs: [5093174,5093231]   #MAGIC and LST runs not to be processed (why?)
    source_name_database: 'CrabNebula'  #MUST BE THE SAME AS IN THE DATABASE
    source_name_output: 'Crab'  #Name to be used in the analysis (will be used in the name of the txt output files), best idea: the same as in the analysis config_general.yaml, WARNING: ONLY ALPHANUMERIC, NO SPECIAL CHARACTERS (special characters can interfere with the analysis scripts)