# A conda environment with all useful package for ctapipe developers
name: magic-lst1
channels:
  - default
  - conda-forge
dependencies:
  - python
  - numpy=1.21
  - astropy~=4.2
  - pip
  - black
  - nbsphinx
  - ctapipe=0.12
  - gammapy=0.19.0
  - h5py
  - ipython
  - jupyter
  - matplotlib=3.5
  - notebook
  - cython
  - graphviz
  - iminuit>=2
  - joblib~=1.2.0
  - numpydoc
  - jupyterlab=3.5.0
  - pandas
  - pre-commit
  - toml
  - protozfits=2.0
  - protobuf=3.20
  - pyparsing
  - psutil
  - pytest
  - pytest-cov
  - pytest-runner
  - pyyaml
  - scikit-learn=1.0
  - sphinx~=4.2
  - sphinx-automodapi
  - sphinx_rtd_theme
  - numba
  - uproot~=4.1
  - corsikaio
  - pymongo
  - seaborn
  - jinja2=3.0 # pinned for bokeh 1.0 compatibility
  - pip:
      - ctapipe_io_lst~=0.18.2
      - ctapipe_io_magic~=0.4.7
      - ctaplot~=0.5.5
      - pyirf~=0.6.0
