name: CI

on: [push, pull_request]

env:
  NUMBA_NUM_THREADS: 1
  MPLBACKEND: Agg
  PYTEST_ADDOPTS: --color=yes

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
        ctapipe-version: [v0.19.2]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set python version ${{ matrix.python-version }}
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          sed -i -e "s/- python.*/- python=$PYTHON_VERSION/g" environment.yml
          echo "Resulting environment file:"
          cat environment.yml

      - name: mamba setup
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-downloads: true

      - name: Install dependencies
        env:
          CTAPIPE_VERSION: ${{ matrix.ctapipe-version }}
        run: |
          python --version
          pip install -e .
          pip install pytest-cov
          pip install pyflakes
          pip install "git+https://github.com/cta-observatory/ctapipe@$CTAPIPE_VERSION"
          ctapipe-info --version | grep "$CTAPIPE_VERSION"
          git describe --tags

      - name: Static codechecks
        run: |
          pyflakes magicctapipe

      #- name: Tests
        #env:
          #MAGIC_CTA_DATA_USER: ${{ secrets.magic_cta_data_user }}
          #MAGIC_CTA_DATA_PASSWORD: ${{ secrets.magic_cta_data_password }}
        #run: |
          #coverage run -m pytest -v
          #coverage xml

      - uses: codecov/codecov-action@v3
